# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.0.20260408"

package:
  name: types-pyfarmhash
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-pyfarmhash/types_pyfarmhash-${{ version }}.tar.gz
  sha256: 1e0480cd567d8b718d519598aa026a435a9b88235700df22d672922665666ea6

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - package_contents:
      site_packages:
        - farmhash-stubs/__init__.pyi
  - python:
      imports: []
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/python/typeshed
  repository: https://github.com/python/typeshed
  summary: Typing stubs for pyfarmhash
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
